<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataSupport extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \Illuminate\Support\Facades\DB::table('data_supports')->insert([[
            'values' => 'chicken',
            'words_vi' => 'con gà',
            'words_en' => 'chicken',
            'voice_vi' => 'conga.mp3',
            'voice_en' => 'chicken.mp3',
            'images' => 'conga.png',
            'key' => 'animal,brown',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'dog',
            'words_vi' => 'con chó',
            'words_en' => 'dog',
            'voice_vi' => 'concho.mp3',
            'voice_en' => 'dog.mp3',
            'images' => 'concho.png',
            'key' => 'animal,brown',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'cat',
            'words_vi' => 'con mèo',
            'words_en' => 'cat',
            'voice_vi' => 'conmeo.mp3',
            'voice_en' => 'cat.mp3',
            'images' => 'conmeo.png',
            'key' => 'animal,White',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'elephant',
            'words_vi' => 'con voi',
            'words_en' => 'elephant',
            'voice_vi' => 'convoi.mp3',
            'voice_en' => 'elephant.mp3',
            'images' => 'convoi.png',
            'key' => 'animal,gray',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'horse',
            'words_vi' => 'con ngựa',
            'words_en' => 'horse',
            'voice_vi' => 'conngua.mp3',
            'voice_en' => 'horse.mp3',
            'images' => 'conngua.png',
            'key' => 'animal,white',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'penguin',
            'words_vi' => 'chim cánh cụt',
            'words_en' => 'penguin',
            'voice_vi' => 'chimcanhcut.mp3',
            'voice_en' => 'penguin.mp3',
            'images' => 'chimcanhcut.png',
            'key' => 'animal,black',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'Dolphin',
            'words_vi' => 'cá heo',
            'words_en' => 'Dolphin',
            'voice_vi' => 'caheo.mp3',
            'voice_en' => 'dolphin.mp3',
            'images' => 'caheo.png',
            'key' => 'animal,blue',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'tiger',
            'words_vi' => 'con hổ',
            'words_en' => 'tiger',
            'voice_vi' => 'conho.mp3',
            'voice_en' => 'tiger.mp3',
            'images' => 'conho.png',
            'key' => 'animal,orange',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'lion',
            'words_vi' => 'sư tử',
            'words_en' => 'lion',
            'voice_vi' => 'sutu.mp3',
            'voice_en' => 'lion.mp3',
            'images' => 'sutu.png',
            'key' => 'animal,rea,orange',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'panda',
            'words_vi' => 'con gấu trúc',
            'words_en' => 'panda',
            'voice_vi' => 'gautruc.mp3',
            'voice_en' => 'panda.mp3',
            'images' => 'gautruc.png',
            'key' => 'animal,black,white',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values' => 'rabbit',
            'words_vi' => 'con thỏ',
            'words_en' => 'rabbit',
            'voice_vi' => 'contho.mp3',
            'voice_en' => 'rabbit.mp3',
            'images' => 'contho.png',
            'key' => 'animal,blue',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values'=> 'turtle',
            'words_vi' => 'con rùa',
            'words_en' => 'turtle',
            'voice_vi' => 'conrua.mp3',
            'voice_en' => 'turtle.mp3',
            'images' => 'conrua.png',
            'key' => 'animal,green',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values'=> 'dinosaur',
            'words_vi' => 'khủng long',
            'words_en' => 'dinosaur',
            'voice_vi' => 'khunglong.mp3',
            'voice_en' => 'dinosaur.mp3',
            'images' => 'khunglong.png',
            'key' => 'animal,green',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ],[
            'values'=> 'fish',
            'words_vi' => 'con cá',
            'words_en' => 'fish',
            'voice_vi' => 'conca.mp3',
            'voice_en' => 'fish.mp3',
            'images' => 'conca.png',
<<<<<<< HEAD
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'giraffe',
            'words_vi' => 'hươu cao cổ',
            'words_en' => 'giraffe',
            'voice_vi' => 'huoucaoco.mp3',
            'voice_en' => 'giraffe.mp3',
            'images' => 'huoucaoco.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'duck',
            'words_vi' => 'con vịt',
            'words_en' => 'duck',
            'voice_vi' => 'convit.mp3',
            'voice_en' => 'duck.mp3',
            'images' => 'convit.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'pig',
            'words_vi' => 'con lợn',
            'words_en' => 'pig',
            'voice_vi' => 'conlon.mp3',
            'voice_en' => 'pig.mp3',
            'images' => 'conlon.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'cows',
            'words_vi' => 'con bò',
            'words_en' => 'cows',
            'voice_vi' => 'conbo.mp3',
            'voice_en' => 'cows.mp3',
            'images' => 'conbo.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'sheep',
            'words_vi' => 'con cừu',
            'words_en' => 'sheep',
            'voice_vi' => 'concuu.mp3',
            'voice_en' => 'sheep.mp3',
            'images' => 'concuu.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'goat',
            'words_vi' => 'con dê',
            'words_en' => 'goat',
            'voice_vi' => 'conde.mp3',
            'voice_en' => 'goat.mp3',
            'images' => 'conde.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'butterfly',
            'words_vi' => 'con bướm',
            'words_en' => 'butterfly',
            'voice_vi' => 'conbuom.mp3',
            'voice_en' => 'butterfly.mp3',
            'images' => 'conbuom.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'donkey',
            'words_vi' => 'con lừa',
            'words_en' => 'donkey',
            'voice_vi' => 'conlua.mp3',
            'voice_en' => 'donkey.mp3',
            'images' => 'conlua.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'deer',
            'words_vi' => 'con nai',
            'words_en' => 'deer',
            'voice_vi' => 'connai.mp3',
            'voice_en' => 'deer.mp3',
            'images' => 'connai.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'shark',
            'words_vi' => 'cá mập',
            'words_en' => 'shark',
            'voice_vi' => 'camap.mp3',
            'voice_en' => 'shark.mp3',
            'images' => 'camap.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'Crocodile',
            'words_vi' => 'cá sấu',
            'words_en' => 'Crocodile',
            'voice_vi' => 'casau.mp3',
            'voice_en' => 'Crocodile.mp3',
            'images' => 'casau.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'frog',
            'words_vi' => 'con ếch',
            'words_en' => 'frog',
            'voice_vi' => 'conech.mp3',
            'voice_en' => 'frog.mp3',
            'images' => 'conech.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'monkey',
            'words_vi' => 'con khỉ',
            'words_en' => 'monkey',
            'voice_vi' => 'conkhi.mp3',
            'voice_en' => 'monkey.mp3',
            'images' => 'conkhi.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'Rhino',
            'words_vi' => 'con tê giác',
            'words_en' => 'Rhino',
            'voice_vi' => 'tegiac.mp3',
            'voice_en' => 'Rhino.mp3',
            'images' => 'tegiac.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'snake',
            'words_vi' => 'con rắn',
            'words_en' => 'snake',
            'voice_vi' => 'conran.mp3',
            'voice_en' => 'snake.mp3',
            'images' => 'conran.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'ostrich',
            'words_vi' => 'đà điểu',
            'words_en' => 'ostrich',
            'voice_vi' => 'dadieu.mp3',
            'voice_en' => 'ostrich.mp3',
            'images' => 'dadieu.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'camel',
            'words_vi' => 'lạc đà',
            'words_en' => 'camel',
            'voice_vi' => 'lacda.mp3',
            'voice_en' => 'camel.mp3',
            'images' => 'lacda.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'parrot',
            'words_vi' => 'con vẹt',
            'words_en' => 'parrot',
            'voice_vi' => 'convet.mp3',
            'voice_en' => 'parrot.mp3',
            'images' => 'convet.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'eagle',
            'words_vi' => 'đại bàng',
            'words_en' => 'eagle',
            'voice_vi' => 'daibang.mp3',
            'voice_en' => 'eagle.mp3',
            'images' => 'daibang.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'unicorn',
            'words_vi' => 'con kì lân',
            'words_en' => 'unicorn',
            'voice_vi' => 'kilan.mp3',
            'voice_en' => 'unicorn.mp3',
            'images' => 'kilan.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'crab',
            'words_vi' => 'con cua',
            'words_en' => 'crab',
            'voice_vi' => 'concua.mp3',
            'voice_en' => 'crab.mp3',
            'images' => 'concua.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'owl',
            'words_vi' => 'cú mèo',
            'words_en' => 'owl',
            'voice_vi' => 'cumeo.mp3',
            'voice_en' => 'owl.mp3',
            'images' => 'cumeo.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'squirrel',
            'words_vi' => 'con sóc',
            'words_en' => 'squirrel',
            'voice_vi' => 'consoc.mp3',
            'voice_en' => 'squirrel.mp3',
            'images' => 'consoc.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'Panther',
            'words_vi' => 'con báo',
            'words_en' => 'Panther',
            'voice_vi' => 'conbao.mp3',
            'voice_en' => 'Panther.mp3',
            'images' => 'conbao.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'Wolf',
            'words_vi' => 'chó sói',
            'words_en' => 'Wolf',
            'voice_vi' => 'chosoi.mp3',
            'voice_en' => 'Wolf.mp3',
            'images' => 'chosoi.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'octopus',
            'words_vi' => 'bạch tuộc',
            'words_en' => 'octopus',
            'voice_vi' => 'bachtuoc.mp3',
            'voice_en' => 'octopus.mp3',
            'images' => 'bachtuoc.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'gorilla',
            'words_vi' => 'tinh tinh',
            'words_en' => 'gorilla',
            'voice_vi' => 'tinhtinh.mp3',
            'voice_en' => 'gorilla.mp3',
            'images' => 'tinhtinh.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'water seal',
            'words_vi' => 'hải cẩu',
            'words_en' => 'water seal',
            'voice_vi' => 'haicau.mp3',
            'voice_en' => 'waterSeal.mp3',
            'images' => 'haicau.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'crawfish',
            'words_vi' => 'con tôm',
            'words_en' => 'crawfish',
            'voice_vi' => 'contom.mp3',
            'voice_en' => 'crawfish.mp3',
            'images' => 'contom.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'snail',
            'words_vi' => 'con ốc sên',
            'words_en' => 'snail',
            'voice_vi' => 'ocsen.mp3',
            'voice_en' => 'snail.mp3',
            'images' => 'ocsen.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'scorpion',
            'words_vi' => 'con bọ cạp',
            'words_en' => 'scorpion',
            'voice_vi' => 'bocap.mp3',
            'voice_en' => 'scorpion.mp3',
            'images' => 'bocap.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'mantis',
            'words_vi' => 'con bọ ngưa',
            'words_en' => 'mantis',
            'voice_vi' => 'bongua.mp3',
            'voice_en' => 'mantis.mp3',
            'images' => 'bongua.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'eel',
            'words_vi' => 'con lươn',
            'words_en' => 'eel',
            'voice_vi' => 'conluon.mp3',
            'voice_en' => 'eel.mp3',
            'images' => 'conluon.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'grasshopper',
            'words_vi' => 'con châu chấu',
            'words_en' => 'grasshopper',
            'voice_vi' => 'chauchau.mp3',
            'voice_en' => 'grasshopper.mp3',
            'images' => 'chauchau.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'Python',
            'words_vi' => 'con trăn',
            'words_en' => 'Python',
            'voice_vi' => 'contran.mp3',
            'voice_en' => 'Python.mp3',
            'images' => 'contran.png',
            'key' => 'animal',
            'createBy' => '0',
        ],[
            'values' => 'bee',
            'words_vi' => 'con ong',
            'words_en' => 'bee',
            'voice_vi' => 'conong.mp3',
            'voice_en' => 'bee.mp3',
            'images' => 'conong.png',
            'key' => 'animal',
            'createBy' => '0',
        ],
=======
            'key' => 'animal,yellow,blue',
            'createBy' => 'hoadvth2009007@fpt.edu.vn',
        ]
>>>>>>> e31b11ffb85c659a5e105afd0a738d523d2949a2
        ]);

    }
}
