<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::table('data_supports')->insert([
            [
                'id' => '0',
                'values' => 'A',
                'words_vi' => 'A',
                'words_en' => 'A',
                'voice_vi' => 'a-vn.mp3',
                'voice_en' => 'a-en.mp3',
                'images' => 'a.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '1',
                'values' => 'B',
                'words_vi' => 'B',
                'words_en' => 'B',
                'voice_vi' => 'b-vn.mp3',
                'voice_en' => 'b-en.mp3',
                'images' => 'b.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '2',
                'values' => 'C',
                'words_vi' => 'C',
                'words_en' => 'C',
                'voice_vi' => 'c-vn.mp3',
                'voice_en' => 'c-en.mp3',
                'images' => 'c.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '3',
                'values' => 'D',
                'words_vi' => 'D',
                'words_en' => 'D',
                'voice_vi' => 'd-vn.mp3',
                'voice_en' => 'd-en.mp3',
                'images' => 'd.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '4',
                'values' => 'E',
                'words_vi' => 'E',
                'words_en' => 'E',
                'voice_vi' => 'e-vn.mp3',
                'voice_en' => 'e-en.mp3',
                'images' => 'e.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '5',
                'values' => 'F',
                'words_vi' => 'F',
                'words_en' => 'F',
                'voice_vi' => 'f-vn.mp3',
                'voice_en' => 'f-en.mp3',
                'images' => 'f.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '6',
                'values' => 'G',
                'words_vi' => 'G',
                'words_en' => 'G',
                'voice_vi' => 'g-vn.mp3',
                'voice_en' => 'g-en.mp3',
                'images' => 'g.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '7',
                'values' => 'H',
                'words_vi' => 'H',
                'words_en' => 'H',
                'voice_vi' => 'h-vn.mp3',
                'voice_en' => 'h-en.mp3',
                'images' => 'h.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '8',
                'values' => 'I',
                'words_vi' => 'I',
                'words_en' => 'I',
                'voice_vi' => 'i-vn.mp3',
                'voice_en' => 'i-en.mp3',
                'images' => 'i.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '9',
                'values' => 'J',
                'words_vi' => 'J',
                'words_en' => 'J',
                'voice_vi' => 'j-vn.mp3',
                'voice_en' => 'j-en.mp3',
                'images' => 'j.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '10',
                'values' => 'K',
                'words_vi' => 'K',
                'words_en' => 'K',
                'voice_vi' => 'k-vn.mp3',
                'voice_en' => 'k-en.mp3',
                'images' => 'k.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '11',
                'values' => 'L',
                'words_vi' => 'L',
                'words_en' => 'L',
                'voice_vi' => 'l-vn.mp3',
                'voice_en' => 'l-en.mp3',
                'images' => 'l.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '12',
                'values' => 'M',
                'words_vi' => 'M',
                'words_en' => 'M',
                'voice_vi' => 'm-vn.mp3',
                'voice_en' => 'm-en.mp3',
                'images' => 'm.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '13',
                'values' => 'N',
                'words_vi' => 'N',
                'words_en' => 'N',
                'voice_vi' => 'n-vn.mp3',
                'voice_en' => 'n-en.mp3',
                'images' => 'n.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '14',
                'values' => 'O',
                'words_vi' => 'O',
                'words_en' => 'O',
                'voice_vi' => 'o-vn.mp3',
                'voice_en' => 'o-en.mp3',
                'images' => 'o.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '15',
                'values' => 'P',
                'words_vi' => 'P',
                'words_en' => 'P',
                'voice_vi' => 'p-vn.mp3',
                'voice_en' => 'p-en.mp3',
                'images' => 'p.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '16',
                'values' => 'Q',
                'words_vi' => 'Q',
                'words_en' => 'Q',
                'voice_vi' => 'q-vn.mp3',
                'voice_en' => 'q-en.mp3',
                'images' => 'q.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '17',
                'values' => 'R',
                'words_vi' => 'R',
                'words_en' => 'R',
                'voice_vi' => 'r-vn.mp3',
                'voice_en' => 'r-en.mp3',
                'images' => 'r.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '18',
                'values' => 'S',
                'words_vi' => 'S',
                'words_en' => 'S',
                'voice_vi' => 's-vn.mp3',
                'voice_en' => 's-en.mp3',
                'images' => 's.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '19',
                'values' => 'T',
                'words_vi' => 'T',
                'words_en' => 'T',
                'voice_vi' => 't-vn.mp3',
                'voice_en' => 't-en.mp3',
                'images' => 't.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '20',
                'values' => 'U',
                'words_vi' => 'U',
                'words_en' => 'U',
                'voice_vi' => 'u-vn.mp3',
                'voice_en' => 'u-en.mp3',
                'images' => 'u.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '21',
                'values' => 'V',
                'words_vi' => 'V',
                'words_en' => 'V',
                'voice_vi' => 'v-vn.mp3',
                'voice_en' => 'v-en.mp3',
                'images' => 'v.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '22',
                'values' => 'W',
                'words_vi' => 'W',
                'words_en' => 'W',
                'voice_vi' => 'w-vn.mp3',
                'voice_en' => 'w-en.mp3',
                'images' => 'w.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '23',
                'values' => 'X',
                'words_vi' => 'X',
                'words_en' => 'X',
                'voice_vi' => 'x-vn.mp3',
                'voice_en' => 'x-en.mp3',
                'images' => 'x.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '23',
                'values' => 'Y',
                'words_vi' => 'Y',
                'words_en' => 'Y',
                'voice_vi' => 'y-vn.mp3',
                'voice_en' => 'y-en.mp3',
                'images' => 'y.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '24',
                'values' => 'Z',
                'words_vi' => 'Z',
                'words_en' => 'Z',
                'voice_vi' => 'z-vn.mp3',
                'voice_en' => 'z-en.mp3',
                'images' => 'z.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '25',
                'values' => '0',
                'words_vi' => 'Không',
                'words_en' => 'zero',
                'voice_vi' => '0-vn.mp3',
                'voice_en' => '0-en.mp3',
                'images' => '0.png',
                'key' => 'character',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '26',
                'values' => '1',
                'words_vi' => 'một',
                'words_en' => 'one',
                'voice_vi' => '1-vn.mp3',
                'voice_en' => '1-en.mp3',
                'images' => '1.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '27',
                'values' => '2',
                'words_vi' => 'hai',
                'words_en' => 'two',
                'voice_vi' => '2-vn.mp3',
                'voice_en' => '2-en.mp3',
                'images' => '2.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '28',
                'values' => '3',
                'words_vi' => 'ba',
                'words_en' => 'three',
                'voice_vi' => '3-vn.mp3',
                'voice_en' => '3-en.mp3',
                'images' => '3.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '29',
                'values' => '4',
                'words_vi' => 'bốn',
                'words_en' => 'four',
                'voice_vi' => '4-vn.mp3',
                'voice_en' => '4-en.mp3',
                'images' => '4.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '30',
                'values' => '5',
                'words_vi' => 'năm',
                'words_en' => 'five',
                'voice_vi' => '5-vn.mp3',
                'voice_en' => '5-en.mp3',
                'images' => '5.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '31',
                'values' => '6',
                'words_vi' => 'sáu',
                'words_en' => 'six',
                'voice_vi' => '6-vn.mp3',
                'voice_en' => '6-en.mp3',
                'images' => '6.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '32',
                'values' => '7',
                'words_vi' => 'bảy',
                'words_en' => 'seven',
                'voice_vi' => '7-vn.mp3',
                'voice_en' => '7-en.mp3',
                'images' => '7.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '33',
                'values' => '8',
                'words_vi' => 'tám',
                'words_en' => 'eight',
                'voice_vi' => '8-vn.mp3',
                'voice_en' => '8-en.mp3',
                'images' => '8.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '34',
                'values' => '9',
                'words_vi' => 'chín',
                'words_en' => 'nine',
                'voice_vi' => '9-vn.mp3',
                'voice_en' => '9-en.mp3',
                'images' => '9.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],[
                'id' => '35',
                'values' => '10',
                'words_vi' => 'mười',
                'words_en' => 'ten',
                'voice_vi' => '10-vn.mp3',
                'voice_en' => '10-en.mp3',
                'images' => '10.png',
                'key' => 'number',
                'createBy' => 'hungpvth2008007@fpt.edu.vn',
            ],
        ]);
    }
}
