<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemSupport extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \Illuminate\Support\Facades\DB::table('data_supports')->insert([
            [
            'values' => 'car',
            'words_vi' => 'oto',
            'words_en' => 'car',
            'voice_vi' => 'oto.mp3',
            'voice_en' => 'car.mp3',
            'images' => 'car.png',
            'key' => 'vehicle,red',
            'createBy' => 'cuongtmth2008049@fpt.edu.vn',
        ],[
            'values' => 'agrimotor',
            'words_vi' => 'máy cày',
            'words_en' => 'agrimotor',
            'voice_vi' => 'maycay.mp3',
            'voice_en' => 'agrimotor.mp3',
            'images' => 'agrimotor.png',
            'key' => 'vehicle,red',
            'createBy' => 'cuongtmth2008049@fpt.edu.vn',
        ]
            ,[
                'values' => 'bike',
                'words_vi' => 'xe đạp',
                'words_en' => 'bike',
                'voice_vi' => 'xedap.mp3',
                'voice_en' => 'bike.mp3',
                'images' => 'bike.png',
                'key' => 'vehicle,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'ambulance',
                'words_vi' => 'xe cứu thương',
                'words_en' => 'ambulance',
                'voice_vi' => 'xecuuthuong.mp3',
                'voice_en' => 'ambulance.mp3',
                'images' => 'ambulance.png',
                'key' => 'vehicle,white',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'ballpoint-pens',
                'words_vi' => 'bút bi',
                'words_en' => 'ballpoint-pens',
                'voice_vi' => 'butbi.mp3',
                'voice_en' => 'ballpoint-pens.mp3',
                'images' => 'ballpoint-pens.png',
                'key' => 'item,baclk',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'board',
                'words_vi' => 'cái bảng',
                'words_en' => 'board',
                'voice_vi' => 'caibang.mp3',
                'voice_en' => 'board.mp3',
                'images' => 'board.png',
                'key' => 'item,Brown',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'bulldozer',
                'words_vi' => 'máy lu',
                'words_en' => 'bulldozer',
                'voice_vi' => 'maylu.mp3',
                'voice_en' => 'bulldozer.mp3',
                'images' => 'bulldozer.png',
                'key' => 'vehicle,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ]
            ,[
                'values' => 'bus',
                'words_vi' => 'xe buýt',
                'words_en' => 'bus',
                'voice_vi' => 'xebuyt.mp3',
                'voice_en' => 'bus.mp3',
                'images' => 'bus.png',
                'key' => 'vehicle,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'camera',
                'words_vi' => 'máy ảnh',
                'words_en' => 'camera',
                'voice_vi' => 'mayanh.mp3',
                'voice_en' => 'camera.mp3',
                'images' => 'camera.png',
                'key' => 'item,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'delivery-truck',
                'words_vi' => 'xe giao hàng',
                'words_en' => 'delivery-truck',
                'voice_vi' => 'xegiaohang.mp3',
                'voice_en' => 'delivery-truck.mp3',
                'images' => 'delivery-truck.png',
                'key' => 'vehicle,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],

            [
                'values' => 'desk',
                'words_vi' => 'bàn học',
                'words_en' => 'desk',
                'voice_vi' => 'banhoc.mp3',
                'voice_en' => 'desk.mp3',
                'images' => 'desk.png',
                'key' => 'item,black',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'drum',
                'words_vi' => 'cái trống',
                'words_en' => 'drum',
                'voice_vi' => 'trong.mp3',
                'voice_en' => 'drum.mp3',
                'images' => 'drum.png',
                'key' => 'item,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ]
            ,[
                'values' => 'Earth-excavator',
                'words_vi' => 'xe xúc',
                'words_en' => 'Earth-excavator',
                'voice_vi' => 'xexuc.mp3',
                'voice_en' => 'Earth-excavator.mp3',
                'images' => 'Earth-excavator.png',
                'key' => 'vehicle,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'eraser',
                'words_vi' => 'cuc tẩy',
                'words_en' => 'eraser',
                'voice_vi' => 'cuctay.mp3',
                'voice_en' => 'eraser.mp3',
                'images' => 'eraser.png',
                'key' => 'item,Orange',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'excavator',
                'words_vi' => 'xe cẩu',
                'words_en' => 'excavator',
                'voice_vi' => 'xecau.mp3',
                'voice_en' => 'excavator.mp3',
                'images' => 'excavator.png',
                'key' => 'vehicle,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'fire-truck',
                'words_vi' => 'xe cứu hỏa',
                'words_en' => 'fire-truck',
                'voice_vi' => 'xecuuhoa.mp3',
                'voice_en' => 'fire-truck.mp3',
                'images' => 'fire-truck.png',
                'key' => 'vehicle,red',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'gamepad',
                'words_vi' => 'tay cầm trò chơi',
                'words_en' => 'gamepad',
                'voice_vi' => 'taycamtrochoi.mp3',
                'voice_en' => 'gamepad.mp3',
                'images' => 'gamepad.png',
                'key' => 'item,black',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ]
            ,[
                'values' => 'gauze-mask',
                'words_vi' => 'khẩu trang',
                'words_en' => 'gauze-mask',
                'voice_vi' => 'khautrang.mp3',
                'voice_en' => 'gauze-mask.mp3',
                'images' => 'gauze-mask.png',
                'key' => 'item,White',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'hairclip',
                'words_vi' => 'kẹp tóc',
                'words_en' => 'hairclip',
                'voice_vi' => 'keptoc.mp3',
                'voice_en' => 'hairclip.mp3',
                'images' => 'hairclip.png',
                'key' => 'item,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'hat',
                'words_vi' => 'mũ',
                'words_en' => 'hat',
                'voice_vi' => 'mu.mp3',
                'voice_en' => 'hat.mp3',
                'images' => 'hat.png',
                'key' => 'item,Brown',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],

            [
                'values' => 'jacket',
                'words_vi' => 'áo khoác',
                'words_en' => 'jacket',
                'voice_vi' => 'aokhoac.mp3',
                'voice_en' => 'jacket.mp3',
                'images' => 'jacket.png',
                'key' => 'item,black',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'lamp',
                'words_vi' => 'đèn ngủ',
                'words_en' => 'lamp',
                'voice_vi' => 'denngu.mp3',
                'voice_en' => 'lamp.mp3',
                'images' => 'lamp.png',
                'key' => 'item,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ]
            ,[
                'values' => 'mixer',
                'words_vi' => 'xe trộn',
                'words_en' => 'mixer',
                'voice_vi' => 'xetron.mp3',
                'voice_en' => 'mixer.mp3',
                'images' => 'mixer.png',
                'key' => 'vehicle,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'moto',
                'words_vi' => 'xe máy',
                'words_en' => 'moto',
                'voice_vi' => 'xemay.mp3',
                'voice_en' => 'moto.mp3',
                'images' => 'moto.png',
                'key' => 'vehicle,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'Numerals',
                'words_vi' => 'hộp số học',
                'words_en' => 'Numerals',
                'voice_vi' => 'hopsohoc.mp3',
                'voice_en' => 'Numerals.mp3',
                'images' => 'Numerals.png',
                'key' => 'item,red',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],

            [
                'values' => 'pen',
                'words_vi' => 'bút mực',
                'words_en' => 'pen',
                'voice_vi' => 'butmuc.mp3',
                'voice_en' => 'pen.mp3',
                'images' => 'pen.png',
                'key' => 'item,black',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'pen-box',
                'words_vi' => 'hộp đựng bút',
                'words_en' => 'pen-box',
                'voice_vi' => 'hopdungbut.mp3',
                'voice_en' => 'pen-box.mp3',
                'images' => 'pen-box.png',
                'key' => 'item,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ]
            ,[
                'values' => 'pencil',
                'words_vi' => 'bút chì',
                'words_en' => 'pencil',
                'voice_vi' => 'butchi.mp3',
                'voice_en' => 'pencil.mp3',
                'images' => 'pencil.png',
                'key' => 'item,black',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'pen-eraser',
                'words_vi' => 'bút tẩy',
                'words_en' => 'pen-eraser',
                'voice_vi' => 'buttay.mp3',
                'voice_en' => 'pen-eraser.mp3',
                'images' => 'pen-eraser.png',
                'key' => 'item,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'planes',
                'words_vi' => 'máy bay',
                'words_en' => 'planes',
                'voice_vi' => 'maybay.mp3',
                'voice_en' => 'planes.mp3',
                'images' => 'planes.png',
                'key' => 'vehicle,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],

            [
                'values' => 'poleax',
                'words_vi' => 'cái rìu',
                'words_en' => 'poleax',
                'voice_vi' => 'riu.mp3',
                'voice_en' => 'poleax.mp3',
                'images' => 'poleax.png',
                'key' => 'item,Gray',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'pots',
                'words_vi' => 'chậu cây',
                'words_en' => 'pots',
                'voice_vi' => 'chaucay.mp3',
                'voice_en' => 'pots.mp3',
                'images' => 'pots.png',
                'key' => 'item,Gray',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ]
            ,[
                'values' => 'rain',
                'words_vi' => 'mưa',
                'words_en' => 'rain',
                'voice_vi' => 'mua.mp3',
                'voice_en' => 'rain.mp3',
                'images' => 'rain.png',
                'key' => 'weather,Gray',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'receiver',
                'words_vi' => 'thu sóng',
                'words_en' => 'receiver',
                'voice_vi' => 'thusong.mp3',
                'voice_en' => 'receiver.mp3',
                'images' => 'receiver.png',
                'key' => 'item,Gray',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'recycle-bin',
                'words_vi' => 'sọt rác',
                'words_en' => 'recycle-bin',
                'voice_vi' => 'sotrac.mp3',
                'voice_en' => 'recycle-bin.mp3',
                'images' => 'recycle-bin.png',
                'key' => 'item,White',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],

            [
                'values' => 'rocket',
                'words_vi' => 'tên lửa',
                'words_en' => 'rocket',
                'voice_vi' => 'tenlua.mp3',
                'voice_en' => 'rocket.mp3',
                'images' => 'rocket.png',
                'key' => 'vehicle,red',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'ruler',
                'words_vi' => 'thước kẻ',
                'words_en' => 'ruler',
                'voice_vi' => 'thuocke.mp3',
                'voice_en' => 'ruler.mp3',
                'images' => 'ruler.png',
                'key' => 'item,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ]
            ,[
                'values' => 'slide',
                'words_vi' => 'cầu trượt',
                'words_en' => 'slide',
                'voice_vi' => 'cautruot.mp3',
                'voice_en' => 'slide.mp3',
                'images' => 'slide.png',
                'key' => 'iteam,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'submarine',
                'words_vi' => 'tàu ngầm',
                'words_en' => 'submarine',
                'voice_vi' => 'taungam.mp3',
                'voice_en' => 'submarine.mp3',
                'images' => 'submarine.png',
                'key' => 'vehicle,black',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'Sun',
                'words_vi' => 'mặt trời',
                'words_en' => 'Sun',
                'voice_vi' => 'mattroi.mp3',
                'voice_en' => 'Sun.mp3',
                'images' => 'Sun.png',
                'key' => 'weather,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],

            [
                'values' => 'sunny',
                'words_vi' => 'cầu vồng',
                'words_en' => 'sunny',
                'voice_vi' => 'cauvong.mp3',
                'voice_en' => 'sunny.mp3',
                'images' => 'sunny.png',
                'key' => 'weather,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'surfboard',
                'words_vi' => 'ván trượt',
                'words_en' => 'surfboard',
                'voice_vi' => 'vantruot.mp3',
                'voice_en' => 'surfboard.mp3',
                'images' => 'surfboard.png',
                'key' => 'item,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ]
            ,[
                'values' => 'taxi',
                'words_vi' => 'taxi',
                'words_en' => 'taxi',
                'voice_vi' => 'xetaxi.mp3',
                'voice_en' => 'taxi.mp3',
                'images' => 'taxi.png',
                'key' => 'vehicle,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'the-subway',
                'words_vi' => 'tàu điện',
                'words_en' => 'the-subway',
                'voice_vi' => 'taudien.mp3',
                'voice_en' => 'the-subway.mp3',
                'images' => 'the-subway.png',
                'key' => 'vehicle,Gray',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'Thunder',
                'words_vi' => 'sấm sét',
                'words_en' => 'Thunder',
                'voice_vi' => 'samset.mp3',
                'voice_en' => 'thunder.mp3',
                'images' => 'thunder.png',
                'key' => 'weather,yellow',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'tow-truck',
                'words_vi' => 'xe cẩu',
                'words_en' => 'tow-truck',
                'voice_vi' => 'xecau.mp3',
                'voice_en' => 'tow-truck.mp3',
                'images' => 'tow-truck.png',
                'key' => 'vehicle,White',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'trash-car',
                'words_vi' => 'xe rác',
                'words_en' => 'trash-car',
                'voice_vi' => 'xerac.mp3',
                'voice_en' => 'trash-car.mp3',
                'images' => 'trash-car.png',
                'key' => 'vehicle,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ]
            ,[
                'values' => 'truck',
                'words_vi' => 'xe ben',
                'words_en' => 'truck',
                'voice_vi' => 'xeben.mp3',
                'voice_en' => 'truck.mp3',
                'images' => 'truck.png',
                'key' => 'vehicle,red',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],[
                'values' => 'cart',
                'words_vi' => 'xe rùa',
                'words_en' => 'cart',
                'voice_vi' => 'xerua.mp3',
                'voice_en' => 'cart.mp3',
                'images' => 'turtle car.png',
                'key' => 'vehicle,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'vase-of-flowers',
                'words_vi' => 'bình nước',
                'words_en' => 'vase-of-flowers',
                'voice_vi' => 'binhnuoc.mp3',
                'voice_en' => 'vase-of-flowers.mp3',
                'images' => 'vase-of-flowers.png',
                'key' => 'item,green',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
            [
                'values' => 'flag',
                'words_vi' => 'lá cờ',
                'words_en' => 'flag',
                'voice_vi' => 'laco.mp3',
                'voice_en' => 'flag.mp3',
                'images' => 'flag.png',
                'key' => 'item,red',
                'createBy' => 'cuongtmth2008049@fpt.edu.vn',
            ],
        ]);


    }
}
